### PR TITLE
Modify USB device port

### PR DESCRIPTION
**Pull request by YaChengMu**
**Closes issue** #

**What has been done in this PR ?**

### CODE REVIEW

**Comment by hieplpvip** [comment]
Are you sure the port for USB-C is SS02?

**Comment by YaChengMu** [comment]
Using aida64 under windows, the port used by USB-C was 10 (2.0), 16 (3.0).

**Comment by YaChengMu** [comment]
My motherboard is u410uqk

**Comment by YaChengMu** [comment]
My motherboard is ux410uqk

**Comment by hieplpvip** [comment]
Thanks. I'll check and merge this

**Comment by hieplpvip** [comment]
@YaChengMu Where did you find the port in aida64 report?

**Comment by YaChengMu** [comment]
yes；
I found it in AIDA64

**Comment by hieplpvip** [comment]
This has been fixed!

**Pull request closed without merging**
